### ISSUE TITLE
Not an issue, just a question of this API

### ISSUE THREAD

**Issue by angelhdzmultimedia** [amacdougall/underscore.as#10]
Hello there!

I love replicating APIs I find from scratch to practice my coding skills. So I made underscore from scratch, using "$" like jQuery, and I noticed in underscore.as there is a "Wrapper". What if the purpose of this? To create instances out of it? 

Thank you!

**Comment by jklmli** [comment]
Hi!  In legacy versions of [underscore.js]() (what underscore.as is based off of), the API supported a deprecated [syntax](https://underscorejs.org/#1.2.4) for chaining multiple operations.  You'd use it like this:

```js
_(fruits)
  .groupBy((fruit) => fruit.color)
  .mapValues((fruitGroup) => fruitGroup.length)
  .value()
```

Now, chaining still exists but has a new API:

```js
_.chain(fruits)
  .groupBy((fruit) => fruit.color)
  .mapValues((fruitGroup) => fruitGroup.length)
  .value()
```

Internally, the point of the wrapper is to hold onto a temporary value, so you can continue to 'chain' additional underscore calls that are not available in the standard browser API.

**Comment by angelhdzmultimedia** [comment]
Thank you very much! Appreciate your time and information.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amacdougall** [comment]
Yep! underscore.as was based on Underscore 1.3, and since Flash was already in its last days when I ported the library, I never updated it to match current usage.
